# -*- coding: utf-8 -*-
"""Exprimental_performnce_rev1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/135DpXZSScfLTMDFK4J0xjyOKbBsZhtu8
"""

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt
import copy
import numpy as np
from collections import deque
import random
import gym # Requires 'gym[atari]' or 'ale-py'
# הגדרת המכשיר (GPU אם זמין)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# הגדרת התמרות
transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.1307,), (0.3081,))])

train_dataset = datasets.MNIST('./data', train=True, download=True, transform=transform)
test_dataset = datasets.MNIST('./data', train=False, transform=transform)

# מחלקה שעוטפת את הנתונים ומערבבת את הפיקסלים אם צריך
class PermutedMNIST(torch.utils.data.Dataset):
    def __init__(self, dataset, permutation=None):
        self.dataset = dataset
        self.permutation = permutation

    def __len__(self):
        return len(self.dataset)

    def __getitem__(self, idx):
        img, label = self.dataset[idx]
        if self.permutation is not None:
            img = img.view(-1)[self.permutation].view(1, 28, 28)
        return img, label

# יצירת מפות ערבוב עבור 6 משימות
perm_A = None # MNIST מקורי
perm_B = torch.randperm(28 * 28)
perm_C = torch.randperm(28 * 28)

# יצירת מפות ערבוב עבור 3 משימות
perm_A = None # MNIST מקורי
perm_B = torch.randperm(28 * 28)
perm_C = torch.randperm(28 * 28)

# שמירת המשימות במילון כדי שיהיה נוח לרוץ עליהן בלולאה
tasks = {
    'A': {
        'train': DataLoader(PermutedMNIST(train_dataset, perm_A), batch_size=64, shuffle=True),
        'test': DataLoader(PermutedMNIST(test_dataset, perm_A), batch_size=1000, shuffle=False)
    },
    'B': {
        'train': DataLoader(PermutedMNIST(train_dataset, perm_B), batch_size=64, shuffle=True),
        'test': DataLoader(PermutedMNIST(test_dataset, perm_B), batch_size=1000, shuffle=False)
    },
    'C': {
        'train': DataLoader(PermutedMNIST(train_dataset, perm_C), batch_size=64, shuffle=True),
        'test': DataLoader(PermutedMNIST(test_dataset, perm_C), batch_size=1000, shuffle=False)
    }
}

print("Permuted MNIST Data ready for 3 Tasks!")

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        # הקטנו את הרשת מ-400 ל-100 נוירונים כדי לאלץ דריסת משקלים מהירה
        self.fc1 = nn.Linear(28 * 28, 100)
        self.fc2 = nn.Linear(100, 100)
        self.fc3 = nn.Linear(100, 10)

    def forward(self, x):
        x = x.view(-1, 28 * 28)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        return self.fc3(x)

def compute_fisher(model, data_loader):
    fisher_matrix = {}
    for name, param in model.named_parameters():
        fisher_matrix[name] = torch.zeros_like(param.data)

    model.eval()
    for data, target in data_loader:
        data, target = data.to(device), target.to(device)
        model.zero_grad()
        output = model(data)
        # חישוב פישר אמפירי מדויק יותר עם log_softmax
        loss = F.nll_loss(F.log_softmax(output, dim=1), target)
        loss.backward()

        for name, param in model.named_parameters():
            if param.grad is not None:
                fisher_matrix[name] += param.grad.data ** 2 / len(data_loader)

    return fisher_matrix


def ewc_penalty_online(model, running_fisher, latest_opt_weights):
    penalty = 0
    for name, param in model.named_parameters():
        fisher = running_fisher[name]
        opt_w = latest_opt_weights[name]
        penalty += (fisher * (param - opt_w) ** 2).sum()
    return penalty

def test_model(model, test_loader):
    model.eval()
    correct = 0
    with torch.no_grad():
        for data, target in test_loader:
            data, target = data.to(device), target.to(device)
            output = model(data)
            pred = output.argmax(dim=1, keepdim=True)
            correct += pred.eq(target.view_as(pred)).sum().item()
    return 100. * correct / len(test_loader.dataset)

d# פרמטרים לפי המאמר (Epochs יכול להיות 20 אם יש לך זמן ריצה, 10 ייתן מגמה טובה)
epochs_per_task = 20
lr = 0.02
lamda = 2000

model_sgd = Net().to(device)
model_ewc = Net().to(device)

optimizer_sgd = optim.SGD(model_sgd.parameters(), lr=lr, momentum=0.9)
optimizer_ewc = optim.SGD(model_ewc.parameters(), lr=lr, momentum=0.9)

fisher_matrices = {}
opt_weights = {}

# מעקב היסטוריה עבור 3 משימות בלבד
history_sgd = {'A': [], 'B': [], 'C': []}
history_ewc = {'A': [], 'B': [], 'C': []}

print("Models initialized. Ready to start training sequence.")

# פרמטרים חדשים ל-Online EWC
alpha = 0.5 # פרמטר "שכחה" עבור הממוצע הנע

running_fisher = {}
latest_opt_weights = {}

total_epochs = 0

for task_id, task_data in tasks.items():
    print(f"\n--- Training on Task {task_id} ---")

    for epoch in range(epochs_per_task):
        model_sgd.train()
        model_ewc.train()

        for batch_idx, (data, target) in enumerate(task_data['train']):
            data, target = data.to(device), target.to(device)

            # --- אימון SGD רגיל ---
            optimizer_sgd.zero_grad()
            output_sgd = model_sgd(data)
            loss_sgd = F.cross_entropy(output_sgd, target)
            loss_sgd.backward()
            optimizer_sgd.step()

            # --- אימון Online EWC ---
            optimizer_ewc.zero_grad()
            output_ewc = model_ewc(data)
            loss_ce = F.cross_entropy(output_ewc, target)

            # שימוש בפונקציית העונש האונליין החדשה (רק אם יש כבר זיכרון)
            loss_ewc = loss_ce
            if len(running_fisher) > 0:
                loss_ewc += (lamda / 2) * ewc_penalty_online(model_ewc, running_fisher, latest_opt_weights)

            loss_ewc.backward()
            optimizer_ewc.step()

        # בדיקת הדיוק ושמירה לגרף...
        # בדיקת הדיוק ושמירה לגרף...
        for test_task_id in tasks.keys():
            history_sgd[test_task_id].append(test_model(model_sgd, tasks[test_task_id]['test']))
            history_ewc[test_task_id].append(test_model(model_ewc, tasks[test_task_id]['test']))

        # יצירת מחרוזת דינמית להדפסה
        ewc_results = ", ".join([f"{k}:{history_ewc[k][-1]:.1f}%" for k in tasks.keys()])
        sgd_results = ", ".join([f"{k}:{history_sgd[k][-1]:.1f}%" for k in tasks.keys()])
        print(f"Epoch {epoch+1:02d} | EWC [{ewc_results}] | SGD [{sgd_results}]")

    # --- הבונוס: עדכון הזיכרון בשיטת Online EWC ---
    print(f"Updating Running Fisher Information for Task {task_id}...")
    current_fisher = compute_fisher(model_ewc, task_data['train'])

    # אם זו המשימה הראשונה, פשוט מאתחלים
    if len(running_fisher) == 0:
        running_fisher = current_fisher
    else:
        # שילוב המידע החדש עם ההיסטוריה בעזרת ממוצע נע אקספוננציאלי
        for name in running_fisher:
            running_fisher[name] = alpha * current_fisher[name] + (1 - alpha) * running_fisher[name]

    # שומרים רק את סט המשקלים האופטימליים האחרון!
    latest_opt_weights = {}
    for name, param in model_ewc.named_parameters():
        latest_opt_weights[name] = param.data.clone()

    total_epochs += epochs_per_task

plt.figure(figsize=(10, 6)) # הוקטן מעט כדי להתאים ל-3 משימות
total_epochs = len(tasks) * epochs_per_task
x_axis = range(1, total_epochs + 1)

# מילון צבעים רק ל-3 משימות
colors = {'A': 'red', 'B': 'green', 'C': 'blue'}

# שרטוט התוצאות של כל המשימות
for t in tasks.keys():
    plt.plot(x_axis, history_ewc[t], label=f'EWC Task {t}', color=colors[t], linestyle='-')
    plt.plot(x_axis, history_sgd[t], label=f'SGD Task {t}', color=colors[t], linestyle='--')

# קווים אנכיים לציון החלפת המשימות
for i in range(1, len(tasks)):
    plt.axvline(x=epochs_per_task * i, color='k', linestyle=':', label='Task Switch' if i == 1 else "")

plt.title('Continual Learning: EWC vs SGD (3 Tasks)')
plt.xlabel('Training Epochs')
plt.ylabel('Test Accuracy (%)')
plt.ylim([10, 105])

# סידור המקרא (Legend) כדי שלא יסתיר את הגרף
# ... (כל הקוד הקיים בתא השרטוט של 3 המשימות) ...

# סידור המקרא (Legend) כדי שלא יסתיר את הגרף
plt.legend(loc='lower left', ncol=3, fontsize='small')
plt.grid(True)

# ---- שורת הקוד להוספה בסוף התא ----
plt.savefig('continual_learning_accuracy.png', dpi=300, bbox_inches='tight')

plt.show()

# --- עיבוד נתונים לגרף הממוצעים ---
task_ids = list(tasks.keys())
num_tasks = len(task_ids)

# נתחיל לצייר ממשימה 2 (כי אחרי משימה 1 עדיין אין "שכחה" של משימות עבר)
x_tasks = range(2, num_tasks + 1)
ewc_avg_acc = []
sgd_avg_acc = []

for i in range(1, num_tasks):
    # חישוב האינדקס של האפוק האחרון של המשימה הנוכחית
    end_epoch = (i + 1) * epochs_per_task - 1

    # המשימות שהמודל כבר ראה עד לנקודה זו (כולל)
    seen_tasks = task_ids[:i+1]

    # שליפת הדיוק של כל המשימות שכבר נלמדו, נכון לסוף המשימה הנוכחית
    ewc_accs = [history_ewc[t][end_epoch] for t in seen_tasks]
    sgd_accs = [history_sgd[t][end_epoch] for t in seen_tasks]

    # חישוב הממוצע ושמירה
    ewc_avg_acc.append(np.mean(ewc_accs))
    sgd_avg_acc.append(np.mean(sgd_accs))

# --- ציור הגרף (בסגנון גרף B מהמאמר) ---
fig, ax = plt.subplots(figsize=(7, 4.5))

ax.plot(x_tasks, ewc_avg_acc, marker='o', color='#c44e52', label='EWC')
ax.plot(x_tasks, sgd_avg_acc, marker='o', color='#4c72b0', label='SGD+dropout')

# קו מקווקו לביצועי משימה בודדת (כאן נניח שהמקסימום שהמודל מגיע אליו הוא סביב 98-100)
# אפשר לשנות את הערך בהתאם למה שיצא לך בגרף A
single_task_baseline = max(history_ewc[task_ids[0]])
ax.axhline(y=single_task_baseline, color='#333333', linestyle='--')

# עיצוב טקסט במקום מקרא רגיל
if len(x_tasks) > 0:
    last_x = x_tasks[-1]
    ax.text(last_x, ewc_avg_acc[-1] - 2, 'EWC', color='#c44e52', fontsize=12, ha='right', va='top')
    ax.text(last_x, sgd_avg_acc[-1] - 2, 'SGD', color='#4c72b0', fontsize=12, ha='right', va='top')
    ax.text(last_x, single_task_baseline + 1, 'single task performance', color='black', fontsize=11, ha='right', va='bottom')

# עיצוב מינימליסטי
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.tick_params(axis='both', direction='out')

ax.set_xlabel('Number of tasks', fontsize=12)
ax.set_ylabel('Average Fraction Correct (%)', fontsize=12)

# ... (כל הקוד הקיים בתא של גרף הממוצעים) ...

# עיצוב מינימליסטי
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.tick_params(axis='both', direction='out')

ax.set_xlabel('Number of tasks', fontsize=12)
ax.set_ylabel('Average Fraction Correct (%)', fontsize=12)

# הגדרת ציר X כך שיציג רק מספרים שלמים של משימות
ax.set_xticks(x_tasks)
plt.tight_layout()

# ---- שורת הקוד להוספה בסוף התא ----
plt.savefig('average_accuracy_fig2b.png', dpi=300, bbox_inches='tight')

plt.show()

# 1. פונקציה לייצור פרמוטציות חלקיות (רק אזור מסוים במרכז מעורבב)
def create_partial_permutation(size):
    perm = torch.arange(28 * 28)
    grid = perm.view(28, 28)

    start = (28 - size) // 2
    end = start + size

    # גזירת האזור המבוקש וערבוב שלו
    region = grid[start:end, start:end].flatten()
    shuffled_region = region[torch.randperm(len(region))]

    # החזרת הערכים המעורבבים למקומם
    grid[start:end, start:end] = shuffled_region.view(size, size)
    return grid.flatten()

# הגדרת הפרמוטציות לפי המאמר (8x8 נמוך, 26x26 גבוה)
perm_base = None
perm_low = create_partial_permutation(8)
perm_high = create_partial_permutation(26)

# הכנת ה-DataLoaders החדשים
batch_size = 64
loader_base = DataLoader(PermutedMNIST(train_dataset, perm_base), batch_size=batch_size, shuffle=True)
loader_low = DataLoader(PermutedMNIST(train_dataset, perm_low), batch_size=batch_size, shuffle=True)
loader_high = DataLoader(PermutedMNIST(train_dataset, perm_high), batch_size=batch_size, shuffle=True)

# 2. אימון רשתות נפרדות לכל משימה כדי למצוא את המשקלים האופטימליים ולחשב פישר
def train_and_get_fisher(dataloader, epochs=2):
    model = Net().to(device)
    optimizer = optim.SGD(model.parameters(), lr=0.02, momentum=0.9)
    model.train()

    # אימון קצר כדי להתכנס לפתרון של המשימה
    for epoch in range(epochs):
        for data, target in dataloader:
            data, target = data.to(device), target.to(device)
            optimizer.zero_grad()
            output = model(data)
            loss = F.cross_entropy(output, target)
            loss.backward()
            optimizer.step()

    # שימוש בפונקציית הפישר שכבר מוגדרת בקוד שלך
    return compute_fisher(model, dataloader)

print("Training models to compute Fisher matrices for overlap graph...")
fisher_base = train_and_get_fisher(loader_base)
fisher_low = train_and_get_fisher(loader_low)
fisher_high = train_and_get_fisher(loader_high)

# 3. חישוב מרחק Fréchet (חפיפה)
def calculate_overlap(f1, f2, layer_name):
    # לקיחת המשקלים של השכבה (ללא הבייס)
    v1 = f1[layer_name + '.weight'].flatten()
    v2 = f2[layer_name + '.weight'].flatten()

    # נרמול ל-unit trace
    v1_hat = v1 / v1.sum()
    v2_hat = v2 / v2.sum()

    # חישוב d^2 לפי נספח 4.3 במאמר
    d2 = 0.5 * torch.sum((torch.sqrt(v1_hat) - torch.sqrt(v2_hat))**2)

    # overlap = 1 - d^2
    return 1.0 - d2.item()

# השכבות שקיימות ברשת שלך (fc1, fc2, fc3)
layers = ['fc1', 'fc2', 'fc3']
overlap_low = [calculate_overlap(fisher_base, fisher_low, l) for l in layers]
overlap_high = [calculate_overlap(fisher_base, fisher_high, l) for l in layers]

# 4. שרטוט הגרף (מקביל ל-Fig 2C)
plt.figure(figsize=(6, 4))
plt.plot(range(1, len(layers)+1), overlap_low, linestyle='-.', marker='.', color='grey', label='low % permutation')
plt.plot(range(1, len(layers)+1), overlap_high, linestyle='--', marker='.', color='black', label='high % permutation')

plt.xlabel('Layer depth', fontsize=12)
plt.ylabel('Overlap in Fisher', fontsize=12)
plt.xticks(range(1, len(layers)+1))
plt.ylim(0, 1.05)

# עיצוב מינימליסטי בדומה למאמר
ax = plt.gca()
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

plt.legend(loc='lower right')
plt.title('Fisher Overlap vs Depth (Fig 2C replication)')

# ---- שורת הקוד להוספה בסוף התא ----
plt.savefig('fisher_overlap_vs_depth_fig2c.png', dpi=300, bbox_inches='tight')

plt.show()

