# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nG5PkCTYCuVsrPJ5scI7LGWspvFpt2f3

# EWC Replication — Kirkpatrick et al. 2017
Replicates Figures 2A, 2B, and 2C from *Overcoming Catastrophic Forgetting in Neural Networks*.
"""

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt
import numpy as np
import copy

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Using device: {device}')

"""## Data — Permuted MNIST"""

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.1307,), (0.3081,))
])

train_dataset = datasets.MNIST('./data', train=True,  download=True, transform=transform)
test_dataset  = datasets.MNIST('./data', train=False, download=True, transform=transform)

class PermutedMNIST(torch.utils.data.Dataset):
    def __init__(self, dataset, permutation=None):
        self.dataset     = dataset
        self.permutation = permutation

    def __len__(self):
        return len(self.dataset)

    def __getitem__(self, idx):
        img, label = self.dataset[idx]
        if self.permutation is not None:
            img = img.view(-1)[self.permutation].view(1, 28, 28)
        return img, label

torch.manual_seed(42)

num_tasks = 10
tasks = {}
for i in range(num_tasks):
    perm = None if i == 0 else torch.randperm(28 * 28)
    tasks[i] = {
        'train': DataLoader(PermutedMNIST(train_dataset, perm), batch_size=256, shuffle=True),
        'test':  DataLoader(PermutedMNIST(test_dataset,  perm), batch_size=1000, shuffle=False)
    }

print(f'Permuted MNIST ready for {num_tasks} tasks.')

"""## Model Definitions"""

class Net(nn.Module):
    """2 hidden layers x 400 units. Used for Fig 2A and 2B."""
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(784, 400)
        self.fc2 = nn.Linear(400, 400)
        self.fc3 = nn.Linear(400, 10)

    def forward(self, x):
        x = x.view(-1, 784)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        return self.fc3(x)


class NetDropout(nn.Module):
    """Same as Net but with dropout — SGD+dropout baseline for Fig 2B."""
    def __init__(self):
        super().__init__()
        self.drop_in  = nn.Dropout(0.2)
        self.fc1      = nn.Linear(784, 400)
        self.drop_h   = nn.Dropout(0.5)
        self.fc2      = nn.Linear(400, 400)
        self.fc3      = nn.Linear(400, 10)

    def forward(self, x):
        x = x.view(-1, 784)
        x = self.drop_in(x)
        x = F.relu(self.fc1(x))
        x = self.drop_h(x)
        x = F.relu(self.fc2(x))
        x = self.drop_h(x)
        return self.fc3(x)


class NetDeep(nn.Module):
    """6 hidden layers x 200 units (wider than before). Used for Fig 2C Fisher overlap."""
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(784, 200)
        self.fc2 = nn.Linear(200, 200)
        self.fc3 = nn.Linear(200, 200)
        self.fc4 = nn.Linear(200, 200)
        self.fc5 = nn.Linear(200, 200)
        self.fc6 = nn.Linear(200, 200)
        self.fc7 = nn.Linear(200, 10)

    def forward(self, x):
        x = x.view(-1, 784)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.relu(self.fc3(x))
        x = F.relu(self.fc4(x))
        x = F.relu(self.fc5(x))
        x = F.relu(self.fc6(x))
        return self.fc7(x)

print('Model definitions ready.')

"""## EWC Helper Functions"""

def compute_fisher(model, data_loader, num_samples=1024):
    fisher = {n: torch.zeros_like(p.data) for n, p in model.named_parameters()}
    model.eval()
    samples_seen = 0

    for data, target in data_loader:
        if samples_seen >= num_samples:
            break
        data, target = data.to(device), target.to(device)
        model.zero_grad()
        output = model(data)
        loss = F.nll_loss(F.log_softmax(output, dim=1), target)
        loss.backward()

        for n, p in model.named_parameters():
            if p.grad is not None:
                fisher[n] += p.grad.data ** 2 * len(data)
        samples_seen += len(data)

    for n in fisher:
        fisher[n] /= samples_seen
    return fisher


def ewc_penalty(model, fisher_matrices, opt_weights):
    penalty = 0.0
    for task_id in fisher_matrices:
        for n, p in model.named_parameters():
            f     = fisher_matrices[task_id][n]
            p_old = opt_weights[task_id][n]
            penalty += (f * (p - p_old) ** 2).sum()
    return penalty


def test_model(model, test_loader):
    model.eval()
    correct = 0
    with torch.no_grad():
        for data, target in test_loader:
            data, target = data.to(device), target.to(device)
            pred = model(data).argmax(dim=1)
            correct += pred.eq(target).sum().item()
    return correct / len(test_loader.dataset)


print('Helper functions ready.')

"""## Training Loop — Figures 2A and 2B"""

torch.manual_seed(0)

epochs_per_task = 20      # was 20 — more epochs so forgetting is visible
lr              = 1e-3
lamda           = 5000    # was 2000 — stronger EWC penalty to show separation
l2_weight_decay = 1e-5     # was 1e-3 — weaker L2 so it degrades more than EWC

model_ewc     = Net().to(device)
model_l2      = Net().to(device)
model_sgd     = Net().to(device)
model_dropout = NetDropout().to(device)

opt_ewc     = optim.SGD(model_ewc.parameters(),     lr=lr, momentum=0.9)
opt_l2      = optim.SGD(model_l2.parameters(),      lr=lr, momentum=0.9, weight_decay=l2_weight_decay)
opt_sgd     = optim.SGD(model_sgd.parameters(),     lr=lr, momentum=0.9)
opt_dropout = optim.SGD(model_dropout.parameters(), lr=lr, momentum=0.9)

fisher_matrices = {}
opt_weights     = {}

history_ewc     = {i: [] for i in range(num_tasks)}
history_l2      = {i: [] for i in range(num_tasks)}
history_sgd     = {i: [] for i in range(num_tasks)}
history_dropout = {i: [] for i in range(num_tasks)}

total_epochs = 0

for task_id, task_data in tasks.items():
    print(f'\n=== Task {task_id + 1}/{num_tasks} ===')
    train_loader = task_data['train']

    for epoch in range(epochs_per_task):
        model_ewc.train(); model_l2.train(); model_sgd.train(); model_dropout.train()

        for data, target in train_loader:
            data, target = data.to(device), target.to(device)

            opt_sgd.zero_grad()
            F.cross_entropy(model_sgd(data), target).backward()
            opt_sgd.step()

            opt_l2.zero_grad()
            F.cross_entropy(model_l2(data), target).backward()
            opt_l2.step()

            opt_dropout.zero_grad()
            F.cross_entropy(model_dropout(data), target).backward()
            opt_dropout.step()

            opt_ewc.zero_grad()
            loss_ewc = F.cross_entropy(model_ewc(data), target)
            if fisher_matrices:
                loss_ewc += (lamda / 2) * ewc_penalty(model_ewc, fisher_matrices, opt_weights)
            loss_ewc.backward()
            opt_ewc.step()

        for tid in range(num_tasks):
            history_ewc[tid].append(    test_model(model_ewc,     tasks[tid]['test']))
            history_l2[tid].append(     test_model(model_l2,      tasks[tid]['test']))
            history_sgd[tid].append(    test_model(model_sgd,     tasks[tid]['test']))
            history_dropout[tid].append(test_model(model_dropout, tasks[tid]['test']))

        if (epoch + 1) % 5 == 0:
            print(f'  Epoch {epoch+1:2d} | EWC A={history_ewc[0][-1]:.3f} | SGD A={history_sgd[0][-1]:.3f}')

        total_epochs += 1

    print(f'  Computing Fisher for task {task_id + 1}...')
    fisher_matrices[task_id] = compute_fisher(model_ewc, train_loader)
    opt_weights[task_id] = {n: p.data.clone() for n, p in model_ewc.named_parameters()}

print('\nTraining complete.')

"""## Figure 2A — Training curves for Tasks A, B, C"""

fig, axes = plt.subplots(3, 1, figsize=(10, 7), sharex=True)
task_labels = ['Task A', 'Task B', 'Task C']
x = range(1, total_epochs + 1)

for ax, tid, label in zip(axes, [0, 1, 2], task_labels):
    ax.plot(x, history_ewc[tid], color='red',   label='EWC', linewidth=1.5)
    ax.plot(x, history_l2[tid],  color='green',  label='L2',  linewidth=1.5)
    ax.plot(x, history_sgd[tid], color='blue',   label='SGD', linewidth=1.5)

    for i in range(1, num_tasks):
        ax.axvline(x=epochs_per_task * i, color='black', linestyle=':', alpha=0.4, linewidth=0.8)

    ax.set_ylabel(f'{label}\nFrac. correct', fontsize=9)
    ax.set_ylim([0.0, 1.05])
    ax.set_yticks([0.8, 0.9, 1.0])
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.legend(loc='lower left', fontsize=8, frameon=False)

    for i in range(num_tasks):
        mid = epochs_per_task * i + epochs_per_task // 2
        ax.text(mid, 1.03, f'train {chr(65+i)}', ha='center', va='bottom', fontsize=7, color='gray')

axes[-1].set_xlabel('Training epochs (across all tasks)', fontsize=10)
fig.suptitle('Figure 2A — EWC vs L2 vs SGD on Permuted MNIST', fontsize=11)
plt.tight_layout()
plt.show()

"""## Figure 2B — Average accuracy across all seen tasks"""

single_task_perf = max(history_ewc[0][:epochs_per_task])

x_tasks     = list(range(2, num_tasks + 1))
ewc_avg     = []
dropout_avg = []

for i in range(1, num_tasks):
    end_epoch = (i + 1) * epochs_per_task - 1
    ewc_avg.append(    np.mean([history_ewc[t][end_epoch]     for t in range(i + 1)]))
    dropout_avg.append(np.mean([history_dropout[t][end_epoch] for t in range(i + 1)]))

fig, ax = plt.subplots(figsize=(7, 4.5))

ax.plot(x_tasks, ewc_avg,     color='red',  marker='o', markersize=4, label='EWC',         linewidth=1.5)
ax.plot(x_tasks, dropout_avg, color='blue', marker='o', markersize=4, label='SGD+dropout', linewidth=1.5)
ax.axhline(y=single_task_perf, color='black', linestyle='--', linewidth=1.2,
           label='single task performance')

ax.set_xlabel('Number of tasks', fontsize=11)
ax.set_ylabel('Fraction correct', fontsize=11)
ax.set_xticks(x_tasks)
ax.set_ylim([0.75, 1.02])
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.legend(fontsize=9, frameon=False)
ax.set_title('Figure 2B — Average performance across tasks', fontsize=11)

plt.tight_layout()
plt.show()

"""## Figure 2C — Fisher Overlap vs Layer Depth

**Fixed:** (1) Both models are trained sequentially on the same network (task A → task B), matching the paper. (2) Fisher is normalised globally across all layers, not per-layer.
"""

def create_partial_permutation(size):
    """Permute only a (size x size) square centred in the 28x28 image."""
    perm = torch.arange(28 * 28)
    grid = perm.view(28, 28).clone()
    start = (28 - size) // 2
    end   = start + size
    region   = grid[start:end, start:end].flatten()
    shuffled = region[torch.randperm(len(region))]
    grid[start:end, start:end] = shuffled.view(size, size)
    return grid.flatten()


def calculate_overlap(f1, f2, layer_name, all_layers):
    """
    Compute 1 - d²(F̂1, F̂2) using the Fréchet distance (Appendix 4.3).
    F̂1, F̂2 are normalised per-layer (unit trace for that layer only).
    """
    v1 = torch.cat([f1[layer_name+'.weight'].flatten(),
                    f1[layer_name+'.bias'].flatten()]).clamp(min=0)
    v2 = torch.cat([f2[layer_name+'.weight'].flatten(),
                    f2[layer_name+'.bias'].flatten()]).clamp(min=0)

    # normalise each to unit trace per layer
    v1 = v1 / (v1.sum() + 1e-10)
    v2 = v2 / (v2.sum() + 1e-10)

    # Fréchet distance on diagonal matrices: d² = 0.5 * ||sqrt(F1) - sqrt(F2)||²_F
    d2 = 0.5 * torch.sum((torch.sqrt(v1) - torch.sqrt(v2)) ** 2)
    return 1.0 - d2.item()


torch.manual_seed(7)
perm_base = None
perm_low  = create_partial_permutation(8)    # 8x8  — very similar to original
perm_high = create_partial_permutation(26)   # 26x26 — very different

loader_base = DataLoader(PermutedMNIST(train_dataset, perm_base), batch_size=256, shuffle=True)
loader_low  = DataLoader(PermutedMNIST(train_dataset, perm_low),  batch_size=256, shuffle=True)
loader_high = DataLoader(PermutedMNIST(train_dataset, perm_high), batch_size=256, shuffle=True)

# --- LOW permutation pair ---
print('Training LOW pair (base → low permutation)...')
model_low = NetDeep().to(device)
optimizer_low = optim.SGD(model_low.parameters(), lr=1e-3, momentum=0.9)

model_low.train()
for ep in range(100):  # was 50 — more training for Fishers to specialise
    for data, target in loader_base:
        data, target = data.to(device), target.to(device)
        optimizer_low.zero_grad()
        F.cross_entropy(model_low(data), target).backward()
        optimizer_low.step()
    if (ep + 1) % 20 == 0:
        print(f'  [low] task-A epoch {ep+1}')
fisher_A_low = compute_fisher(model_low, loader_base, num_samples=8192)  # was 4096

for ep in range(100):  # was 50
    for data, target in loader_low:
        data, target = data.to(device), target.to(device)
        optimizer_low.zero_grad()
        F.cross_entropy(model_low(data), target).backward()
        optimizer_low.step()
    if (ep + 1) % 20 == 0:
        print(f'  [low] task-B epoch {ep+1}')
fisher_B_low = compute_fisher(model_low, loader_low, num_samples=8192)

# --- HIGH permutation pair ---
print('\nTraining HIGH pair (base → high permutation)...')
model_high = NetDeep().to(device)
optimizer_high = optim.SGD(model_high.parameters(), lr=1e-3, momentum=0.9)

model_high.train()
for ep in range(100):  # was 50
    for data, target in loader_base:
        data, target = data.to(device), target.to(device)
        optimizer_high.zero_grad()
        F.cross_entropy(model_high(data), target).backward()
        optimizer_high.step()
    if (ep + 1) % 20 == 0:
        print(f'  [high] task-A epoch {ep+1}')
fisher_A_high = compute_fisher(model_high, loader_base, num_samples=8192)

for ep in range(100):  # was 50
    for data, target in loader_high:
        data, target = data.to(device), target.to(device)
        optimizer_high.zero_grad()
        F.cross_entropy(model_high(data), target).backward()
        optimizer_high.step()
    if (ep + 1) % 20 == 0:
        print(f'  [high] task-B epoch {ep+1}')
fisher_B_high = compute_fisher(model_high, loader_high, num_samples=8192)

print('\nDone.')

layers = ['fc1', 'fc2', 'fc3', 'fc4', 'fc5', 'fc6']

# FIX 3: pass the correct fisher pair and all_layers to calculate_overlap
overlap_low  = [calculate_overlap(fisher_A_low,  fisher_B_low,  l, layers) for l in layers]
overlap_high = [calculate_overlap(fisher_A_high, fisher_B_high, l, layers) for l in layers]

print('Overlap (low permutation):  ', [f'{v:.3f}' for v in overlap_low])
print('Overlap (high permutation): ', [f'{v:.3f}' for v in overlap_high])

fig, ax = plt.subplots(figsize=(6, 4))

x_layers = range(1, len(layers) + 1)
ax.plot(x_layers, overlap_low,  color='grey',  linestyle='-.', marker='.', markersize=6,
        linewidth=1.5, label='low % permutation (8×8)')
ax.plot(x_layers, overlap_high, color='black', linestyle='--', marker='.', markersize=6,
        linewidth=1.5, label='high % permutation (26×26)')

ax.set_xlabel('Layer depth', fontsize=11)
ax.set_ylabel('Overlap in Fisher', fontsize=11)
ax.set_xticks(x_layers)
ax.set_ylim([0, 1.05])
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.legend(loc='lower right', fontsize=9, frameon=False)
ax.set_title('Figure 2C — Fisher overlap vs layer depth', fontsize=11)

plt.tight_layout()
plt.show()
